export const localMenus = [
    {
        id: 1463,
        parentId: 0,
        code: 'gateway',
        name: 'Gateway',
        sysTypeId: 10,
        levelId: 1,
    },
    {
        id: 1464,
        parentId: 0,
        code: 'routerSetting',
        name: 'RouterSetting',
        sysTypeId: 10,
        levelId: 1,
    },

    {
        id: 1467,
        parentId: 0,
        code: 'permission',
        name: 'Permission',
        sysTypeId: 10,
        levelId: 1,
    },
    {
        id: 1469,
        parentId: 1467,
        code: 'button',
        name: 'Button',
        sysTypeId: 10,
        levelId: 2,
    },
    {
        id: 1470,
        parentId: 1467,
        code: 'module',
        name: 'Module',
        sysTypeId: 10,
        levelId: 2,
    },

    {
        id: 1570,
        parentId: 0,
        code: 'nested',
        name: 'Nested',
        sysTypeId: 10,
        levelId: 1,
    },
    {
        id: 1471,
        parentId: 1570,
        code: 'm-1',
        name: 'm-1',
        sysTypeId: 10,
        levelId: 2,
    },

    {
        id: 1701,
        parentId: 1471,
        code: 'm-1-1',
        name: 'm-1-1',
        sysTypeId: 10,
        levelId: 3,
    },

    {
        id: 1702,
        parentId: 1471,
        code: 'm-1-2',
        name: 'm-1-2',
        sysTypeId: 10,
        levelId: 3,
    },
    // {
    //     id: 1801,
    //     parentId: 1702,
    //     code: 'm-1-2-1',
    //     name: 'm-1-2-1',
    //     sysTypeId: 10,
    //     levelId: 4,
    // },
    {
        id: 1802,
        parentId: 1702,
        code: 'm-1-2-2',
        name: 'm-1-2-2',
        sysTypeId: 10,
        levelId: 4,
    },

    {
        id: 1703,
        parentId: 1471,
        code: 'm-1-3',
        name: 'm-1-3',
        sysTypeId: 10,
        levelId: 3,
    },

    {
        id: 1472,
        parentId: 1570,
        code: 'm-2',
        name: 'm-2',
        sysTypeId: 10,
        levelId: 2,
    },
    {
        id: 1900,
        parentId: 0,
        code: 'special-level-home',
        name: 'special-level-home',
        sysTypeId: 10,
        levelId: 1,
    },
    {
        id: 1910,
        parentId: 0,
        code: 'special-level-2',
        name: 'special-level-2',
        sysTypeId: 10,
        levelId: 1,
    },
    {
        id: 1920,
        parentId: 0,
        code: 'statistic',
        name: 'statistic',
        sysTypeId: 10,
        levelId: 1,
    },
];
